### PR TITLE
Torch Clip Fixed

### LINKED ISSUE #23: Fix torch clipping through cave walls.

### PR DESCRIPTION
**Pull request by bchorne**
Torch gets layers set to "Torch" on pickup, also applied to its children.
Main camera draws everything except the Torch, the TorchCam only draws the torch on a higher depth.

### CODE REVIEW

**Comment by Sharkules** [comment]
Works great! The only problem I've seen is that the torch is casting a ring shadow on the wall, but it does stop once you pick up the torch.
It can be fixed by turning 'cast shadows' off on the torch mesh, should I do that and push the change?
There's also a nullref when you try to crouch, easy fix though.

image
image

**Comment by bchorne** [comment]
Yeah, good idea, while you're at it you can also delete that other light on the torch, the back one. It's not needed since I moved the light further back in the torch to prevent issues with the light source clipping through the wall. If you're going to merge, make sure to accept all incoming changes here, remove whatever is in main with what's in here.

**Comment by bchorne** [comment]
Though now that I've said that, there might be a serious scene conflict there. Hopefully it'll be fine enough, I'll check after the merge.

**Comment by bchorne** [comment]
Yeah, I made a mistake, I branched this before sfx was merged in I think, so now we have main with the Sound changes in Game and this branch with the Torch changes in Game. I'm going to make the torchcam here a prefab, and then it should be fine to overwrite this branches Scene file with what's on Main.

**Comment by Sharkules** [comment]
Double checking - do you want me to pull main and remove shadows + extra light, or did you fix that up while you were prefabbing?

**Pull request merged**
